
[functions.send-push]
enabled = true
verify_jwt = true
import_map = "./functions/send-push/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/send-push/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/send-push/*.html" ]

[functions.fincra-create-payin]
enabled = true
verify_jwt = true
import_map = "./functions/fincra-create-payin/deno.json"
entrypoint = "./functions/fincra-create-payin/index.ts"

[functions.fincra-webhook]
enabled = true
verify_jwt = false
import_map = "./functions/fincra-webhook/deno.json"
entrypoint = "./functions/fincra-webhook/index.ts"

[functions.fincra-create-payout]
enabled = true
verify_jwt = true
import_map = "./functions/fincra-create-payout/deno.json"
entrypoint = "./functions/fincra-create-payout/index.ts"

[functions.fincra-fund-wallet]
enabled = true
verify_jwt = false
import_map = "./functions/fincra-fund-wallet/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/fincra-fund-wallet/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/fincra-fund-wallet/*.html" ]

[functions.fincra-payin-webhook]
enabled = true
verify_jwt = false
import_map = "./functions/fincra-payin-webhook/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/fincra-payin-webhook/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/fincra-payin-webhook/*.html" ]

[functions.fincra-list-banks]
enabled = true
verify_jwt = false
import_map = "./functions/fincra-list-banks/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/fincra-list-banks/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/fincra-list-banks/*.html" ]

[functions.fincra-verify-account]
enabled = true
verify_jwt = false
import_map = "./functions/fincra-verify-account/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/fincra-verify-account/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/fincra-verify-account/*.html" ]

[functions.fincra-payout]
enabled = true
verify_jwt = false
import_map = "./functions/fincra-payout/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/fincra-payout/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/fincra-payout/*.html" ]

[functions.fincra-payout-webhook]
enabled = true
verify_jwt = false
import_map = "./functions/fincra-payout-webhook/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/fincra-payout-webhook/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/fincra-payout-webhook/*.html" ]

[functions.fincra-verify-payment]
enabled = true
verify_jwt = false
import_map = "./functions/fincra-verify-payment/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/fincra-verify-payment/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/fincra-verify-payment/*.html" ]
